### PR TITLE
[CS-5837] [New Feature] add support for other editors in smarty link function

### PR DESCRIPTION
**Pull request by ahilles107**
Add smarty function generate_edit_url

Documentation is here: https://wiki.sourcefabric.org/display/NsLingo/Generate+uri+for+editing+article+from+frontend

### CODE REVIEW

**Comment by ahilles107** [comment]
@danielhjames - where exactly i should put documentation for that new smarty function?

**Comment by danielhjames** [comment]
That is a good question. I will ask Holman and Gideon about the tech docs now that Sam has left.

**Comment by ahilles107** [comment]
but this is new smarty feature so looks like it should go to templators documentation - but where exaclty.

**Comment by danielhjames** [comment]
Trouble is that there is more than one set of templators documentation, including http://sourcefabric.readthedocs.org/en/latest/ and https://wiki.sourcefabric.org/display/NsLingo/Newscoop+Template+Reference and http://sourcefabric.booktype.pro/newscoop-43-cookbook/ :-)

**Comment by ahilles107** [comment]
ok, try to get information where we should update it ;)

**Pull request merged**
