### PR TITLE
CS-5875 Remove more images not referenced in current source code

### PR DESCRIPTION
**Pull request by danielhjames**
I discovered some more image files which are not found when searching current master branch source with grep.

### CODE REVIEW

**Comment by ahilles107** [comment]
spec/assets/images/picture.jpg is used in specs, please exclude it from that pr

**Comment by danielhjames** [comment]
I did wonder about that file, I could see no direct reference to it in specs any more. It's removed from the removal :-)

**Comment by ahilles107** [comment]
it's used for example here: ```spec/Newscoop/Image/ImageServiceSpec.php```

**Comment by danielhjames** [comment]
I see that now, thanks. Not sure how I missed that :-)

**Pull request merged**
