### PR TITLE
CS-5802 - Featured Article List limits do not work as expected

### PR DESCRIPTION
**Pull request by takeit**
This PR fixes the issue with limit's modal. 
**Initially if there is no limit set for the list and:**
- you want to set the limit - a prompt will popup
- limit is the same and you click the save btn - no prompt will popup

**Initially there is a limit set for the list and:**
- you want to increase the limit - no prompt will popup
- you want to decrease the limit (but the new limit is not 0 or "empty value") - a prompt will popup
- you want to decrease the limit (a new limit is set to 0 or "empty value") - no prompt will popup

It will remove articles over the set limit instantly when changing the limit value accordingly.

### CODE REVIEW

**Comment by ahilles107** [comment]
How about removing items from list (ui) immediately after decreasing limit ?

**Comment by takeit** [comment]
@ahilles107 without a prompt ?

**Comment by ahilles107** [comment]
with a prompt - when you realy want ot remove left articles

**Comment by ahilles107** [comment]
:+1:

**Pull request merged**
